function newNote(locals) {
var jade_debug = [ new jade.DebugItem( 1, "newNote.jade" ) ];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (note) {
jade_debug.unshift(new jade.DebugItem( 0, "newNote.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "newNote.jade" ));
buf.push("<div class=\"note__card mdl-card mdl-shadow--4dp animated bounceInLeft\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 2, "newNote.jade" ));
buf.push("<form class=\"newNote\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 3, "newNote.jade" ));
buf.push("<div class=\"error__message\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 4, "newNote.jade" ));
buf.push("<span>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 5, "newNote.jade" ));
buf.push("<div class=\"note__card__progress mdl-progress mdl-js-progress mdl-progress__indeterminate\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 6, "newNote.jade" ));
buf.push("<div class=\"mdl-card__title\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 7, "newNote.jade" ));
buf.push("<div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 8, "newNote.jade" ));
buf.push("<input id=\"new-note__title\" type=\"text\" name=\"title\" class=\"mdl-textfield__input\"/>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 9, "newNote.jade" ));
buf.push("<label for=\"new-note__title\" class=\"mdl-textfield__label\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 9, jade_debug[0].filename ));
buf.push("Title");
jade_debug.shift();
jade_debug.shift();
buf.push("</label>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 10, "newNote.jade" ));
buf.push("<div class=\"mdl-card__supporting-text\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 11, "newNote.jade" ));
buf.push("<div class=\"mdl-textfield mdl-js-textfield\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 12, "newNote.jade" ));
buf.push("<textarea id=\"sample5\" type=\"text\" rows=\"3\" name=\"content\" class=\"mdl-textfield__input\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</textarea>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 13, "newNote.jade" ));
buf.push("<label for=\"sample5\" class=\"mdl-textfield__label\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 13, jade_debug[0].filename ));
buf.push("Note Text");
jade_debug.shift();
jade_debug.shift();
buf.push("</label>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 14, "newNote.jade" ));
buf.push("<div class=\"mdl-card__actions\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 15, "newNote.jade" ));
buf.push("<button" + (jade.cls(['edit','mdl-button','mdl-button--colored','mdl-js-button','mdl-js-ripple-effect','' + (note.alias) + ''], [null,null,null,null,null,true])) + ">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 16, "newNote.jade" ));
buf.push("<i class=\"material-icons\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 16, jade_debug[0].filename ));
buf.push("edit");
jade_debug.shift();
jade_debug.shift();
buf.push("</i>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 17, "newNote.jade" ));
buf.push("Edit");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 18, "newNote.jade" ));
buf.push("<button" + (jade.cls(['delete','mdl-button','mdl-button--colored','mdl-js-button','mdl-js-ripple-effect','' + (note.alias) + ''], [null,null,null,null,null,true])) + ">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 19, "newNote.jade" ));
buf.push("<i class=\"material-icons\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 19, jade_debug[0].filename ));
buf.push("delete");
jade_debug.shift();
jade_debug.shift();
buf.push("</i>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 20, "newNote.jade" ));
buf.push("Delete");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</form>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();}.call(this,"note" in locals_for_with?locals_for_with.note:typeof note!=="undefined"?note:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, ".note__card.mdl-card.mdl-shadow--4dp.animated.bounceInLeft\n  form.newNote\n    .error__message\n      span\n    .note__card__progress.mdl-progress.mdl-js-progress.mdl-progress__indeterminate\n    .mdl-card__title\n      .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label\n        input#new-note__title.mdl-textfield__input(type='text',name='title')\n        label.mdl-textfield__label(for='new-note__title') Title\n    .mdl-card__supporting-text\n      .mdl-textfield.mdl-js-textfield\n        textarea#sample5.mdl-textfield__input(type='text', rows='3', name='content')\n        label.mdl-textfield__label(for='sample5') Note Text\n    .mdl-card__actions\n      button.edit.mdl-button.mdl-button--colored.mdl-js-button.mdl-js-ripple-effect(class='#{note.alias}')\n        i.material-icons edit\n        | Edit\n      button.delete.mdl-button.mdl-button--colored.mdl-js-button.mdl-js-ripple-effect(class='#{note.alias}')\n        i.material-icons delete\n        | Delete\n");
}
}